on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-main
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: docker build . --file docker/Dockerfile --tag mgovers-docker-test:0.0.2

      - name: set latest tag
        run: |
          docker tag mgovers-docker-test:0.0.2 mgovers-docker-test:latest
          docker tag mgovers-docker-test:0.0.2 mgovers-docker-test:$(date +%Y%m%d%H%M%S)

      - name: list images
        run: docker image ls

      - name: save container
        run: |
          docker save mgovers-docker-test | gzip > mgovers-docker-test.tar.gz

      - name: Keep wheel files
        uses: actions/upload-artifact@v4
        with:
          name: mgovers-docker-test.tar.gz
          path: mgovers-docker-test.tar.gz

  test-cpp-build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: mgovers-docker-test.tar.gz
          path: .

      - name: load container
        run: |
          docker load < mgovers-docker-test.tar.gz
          docker image ls

      - name: run tests
        run: |
          docker run --name mgovers-runtime -d -i -t mgovers-docker-test
          docker exec mgovers-runtime sh -c "git clone https://github.com/PowerGridModel/power-grid-model.git && cd power-grid-model && git status && sh ./build.sh -p gcc-debug -e -i -t"

  test-python-build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: mgovers-docker-test.tar.gz
          path: .

      - name: load container
        run: |
          docker load < mgovers-docker-test.tar.gz
          docker image ls

      - name: run tests
        run: |
          docker run --name mgovers-runtime -d -i -t mgovers-docker-test
          docker exec mgovers-runtime sh -c "pipx ensurepath && pipx install --include-deps pytest && git clone https://github.com/PowerGridModel/power-grid-model.git && cd power-grid-model && CC=gcc CXX=g++ pipx install --include-deps -e .[dev] && /home/user/.local/pipx/venvs/bin/pytest"
