on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: docker build . --file docker/Dockerfile --tag mgovers-docker-test:0.0.1
      
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v4

      - name: run tests
        run: |
          docker exec mgovers-docker-test:0.0.1 ./scripts/test.sh
