on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: docker build . --file docker/Dockerfile --tag mgovers-docker-test:0.0.1

      - name: set latest tag
        run: |
          docker tag mgovers-docker-test:0.0.1 mgovers-docker-test:latest
          docker tag mgovers-docker-test:0.0.1 mgovers-docker-test:$(date +%Y%m%d%H%M%S)

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v4

      - name: list images
        run: docker image ls

      - name: save container
        run: |
          docker create --name mgovers-docker-test mgovers-docker-test:0.0.1
          docker cp mgovers-docker-test:/home/mgovers/target/mgovers-*.jar ./mgovers.jar
          docker save -o mgovers-docker-test.tar mgovers-docker-test

      - name: Keep wheel files
        uses: actions/upload-artifact@v4
        with:
          name: mgovers-docker-image
          path: mgovers-docker-image.tar

      - name: run tests
        run: |
          docker run --name mgovers-runtime -d -i -t mgovers-docker-test
          docker exec mgovers-runtime sh ./scripts/run.sh
