on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: docker build . --file docker/Dockerfile --tag mgovers-docker-test:0.0.1

      - name: set latest tag
        run: |
          docker tag mgovers-docker-test:0.0.1 mgovers-docker-test:latest
          docker tag mgovers-docker-test:0.0.1 mgovers-docker-test:$(date +%Y%m%d%H%M%S)

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v4

      - name: run tests
        run: |
          docker run --name mgovers-runtime -d -i -t mgovers-docker-test
          docker exec mgovers-runtime sh ./scripts/test.sh
