on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: docker build . --file docker/Dockerfile --tag mgovers-docker-test:0.0.1

      - name: set latest tag
        run: |
          docker tag mgovers-docker-test:0.0.1 mgovers-docker-test:latest
          docker tag mgovers-docker-test:0.0.1 mgovers-docker-test:$(date +%Y%m%d%H%M%S)

      - name: list images
        run: docker image ls

  #     - name: save container
  #       run: |
  #         docker save mgovers-docker-test | gzip > mgovers-docker-test.tar.gz

  #     - name: Keep wheel files
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: mgovers-docker-test
  #         path: mgovers-docker-test.tar.gz

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v4

  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: version
  #         commit: eb0e7f4
  #         path: .

      - name: run tests
        run: |
          docker run --name mgovers-runtime -d -i -t mgovers-docker-test
          docker exec mgovers-runtime "git clone https://github.com/PowerGridModel/power-grid-model.git && cd power-grid-model && git status && sh ./build.sh -p gcc_debug -e -i -t"

